### ISSUE TITLE
 local variable 'twname' referenced before assignment

### ISSUE THREAD

**Issue by White2001Offl** [DoubleThreatSecurity/Scylla#11]
I'm getting an error while running script
```
Traceback (most recent call last):
  File "scylla.py", line 1181, in <module>
    main()
  File "scylla.py", line 1097, in main
    cprint(Twitter(args.twitter).RetrieveAccountInformation(), 'green', attrs=['bold'])
  File "scylla.py", line 867, in RetrieveAccountInformation
    '''.format(str(twname), str(data['Bio: ']),
UnboundLocalError: local variable 'twname' referenced before assignment
```
What could be the issue?

**Comment by Josue87** [comment]
**Line 807** fails: **twname = soup.title.text.split("|")[0]**.   soup.title is None, therefore the variable is not defined.  At **line 867** ('''.format(str(**twname**), str(data['Bio: ']),), an attempt is made to use it, but there is no such variable.
