### ISSUE TITLE
Couldn't find index page for 'urllib'

### ISSUE THREAD

**Issue by imbdan01** [DoubleThreatSecurity/Scylla#2]
I've tried to install all the requirements but I'm still stuck with urllib.

sudo python3 setup.py install
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing Scylla.egg-info/PKG-INFO
writing dependency_links to Scylla.egg-info/dependency_links.txt
writing requirements to Scylla.egg-info/requires.txt
writing top-level names to Scylla.egg-info/top_level.txt
reading manifest file 'Scylla.egg-info/SOURCES.txt'
writing manifest file 'Scylla.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Scylla.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Scylla.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Scylla.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Scylla.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Scylla.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Scylla-1.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Scylla-1.0-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/Scylla-1.0-py3.6.egg
Copying Scylla-1.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Scylla 1.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/Scylla-1.0-py3.6.egg
Processing dependencies for Scylla==1.0
Searching for urllib
Reading https://pypi.python.org/simple/urllib/
Couldn't find index page for 'urllib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for urllib
error: Could not find suitable distribution for Requirement.parse('urllib')

**Comment by josh0xA** [comment]
Hey man. I've added a requirments.txt script. Please read over the new installation instructions. I will be removing the setup.py script.

**Comment by imbdan01** [comment]
Thanks Josh!
